export const MAKES = [
  "Acura",
  "Audi",
  "BMW",
  "Buick",
  "cadillac",
  "chevy",
  "Chrysler",
  "Dodge",
  "Ford",
  "GMC",
  "Honda",
  "hyundai",
  "infiniti",
  "isuzu",
  "Jaguar",
  "Jeep",
  "kia",
  "LandRover",
  "Lexus",
  "Lincoln",
  "Mazda",
  "Mercedes",
  "Nissan",
  "Pontiac",
  "Porsche",
  "Saturn",
  "subaru",
  "suzuki",
  "Toyota",
  "Volvo",
  "Volkswagen"
];

export const MODELS: Record<string, string[]> = {
  Ford: [
    "500",
    "Aerostar",
    "Aspire",
    "Bronco (Full Size)",
    "Bronco II",
    "C-Max",
    "Contour",
    "Crown Vic",
    "Ecosport",
    "Edge",
    "Escape",
    "Escort",
    "Excursion",
    "Expedition",
    "Explorer",
    "Festiva",
    "Fiesta",
    "Five Hundred",
    "Flex",
    "Focus",
    "Focus RS",
    "Freestar",
    "Freestyle",
    "Fusion",
    "GT",
    "Mustang",
    "Probe",
    "Ranger",
    "Taurus",
    "Taurus X",
    "Tempo",
    "Thunderbird",
    "Transit 150",
    "Transit 250",
    "Transit 350",
    "Transit Connect",
    "Truck-F150",
    "Truck-F150 Raptor",
    "Truck-F250 not Super Duty",
    "Truck-F250 Super Duty",
    "Truck-F350 not Super Duty",
    "Truck-F350 Super Duty",
    "Truck-F450 not Super Duty",
    "Truck-F450 Super Duty",
    "Truck-F550 Super Duty",
    "Truck-Ranger",
    "Van E150",
    "Van E250",
    "Van E350",
    "Van E450 Super Duty",
    "Van E550 Super Duty",
    "Windstar"
  ],
  GMC: [
    "Acadia",
    "Jimmy, Full Size",
    "Jimmy, S10/S15",
    "Safari Van",
    "Suburban-1500",
    "Suburban-2500",
    "Syclone",
    "Terrain",
    "Truck-1500 Series",
    "Truck-2500 Series",
    "Truck-3500 Series",
    "Truck-Canyon",
    "Truck-Envoy",
    "Truck-Envoy XL",
    "Truck-Envoy XUV",
    "Truck-Forward Control",
    "Truck-S10/S15/Sonoma",
    "Truck-Sierra 1500",
    "Truck-Sierra 2500",
    "Truck-Sierra 3500",
    "Truck-Sierra Denali",
    "Truck-Sierra Denali 1500",
    "Truck-Sierra Denali 2500",
    "Truck-Sierra Denali 3500",
    "Truck-Yukon (except XL)",
    "Truck-Yukon XL1500",
    "Truck-Yukon XL2500",
    "Typhoon",
    "Van 1500",
    "Van 2500",
    "Van 3500",
    "Van Savana 1500",
    "Van Savana 2500",
    "Van Savana 3500"
  ],
  isuzu: [
    "Amigo",
    "Ascender",
    "Axiom",
    "Oasis",
    "Rodeo",
    "Trooper/Trooper II",
    "Truck-(Mini Pickup)",
    "Truck i280 (Pickup)",
    "Truck i290 (Pickup)",
    "Truck i350 (Pickup)",
    "Truck i370 (Pickup)",
    "Vehicross"
  ],
  Jaguar: [
    "F Pace",
    "F Type",
    "S Type",
    "Vanden Plas",
    "X Type",
    "XE",
    "XF",
    "XJ Series",
    "XJ6",
    "XJ8",
    "XJ12",
    "XJR",
    "XJS",
    "XK Series",
    "XK8",
    "XKR"
  ],
  Volkswagen: [
    "Beetle/Bug",
    "Cabrio",
    "Cabriolet",
    "CC",
    "Corrado",
    "Eos",
    "Golf",
    "Golf GTI",
    "Jetta",
    "Jetta GLI",
    "Passat",
    "Phaeton",
    "Rabbit",
    "Routan",
    "Tiguan",
    "Touareg",
    "Van-EuroVan"
  ],
  kia: [
    "Amanti",
    "Borrego",
    "Cadenza",
    "Forte",
    "K900",
    "Magentis",
    "Optima",
    "Rio",
    "Rondo",
    "Sedona",
    "Sephia",
    "Sorento",
    "Soul",
    "Spectra",
    "Sportage"
  ],
  hyundai: [
    "Accent",
    "Azera",
    "Elantra",
    "Entourage",
    "Equus",
    "Genesis",
    "Ioniq",
    "Kona",
    "Santa Fe",
    "Scoupe",
    "Sonata",
    "Tiburon",
    "Tucson",
    "Veloster",
    "Veracruz",
    "XG Series"
  ],
  LandRover: [
    "Defender",
    "Discovery",
    "Discovery Sport",
    "Freelander",
    "LR2",
    "LR3",
    "LR4",
    "Range Rover",
    "Range Rover Evoque",
    "Range Rover Sport"
  ],
  Pontiac: [
    "Aztek",
    "Bonneville (1980 Up)",
    "Firebird",
    "Firefly",
    "G3",
    "G5",
    "G6",
    "G8",
    "Grand AM",
    "Grand Prix",
    "GTO (New Style)",
    "Montana",
    "Pursuit",
    "Solstice",
    "Sunfire",
    "Sunrunner",
    "Torrent",
    "Trans Sport",
    "Van-Montana",
    "Vibe",
    "Wave"
  ],
  Honda: [
    "Accord",
    "Civic",
    "Crosstour",
    "CRV",
    "CRZ",
    "Element",
    "Fit",
    "HRV",
    "Insight",
    "Odyssey",
    "Passport",
    "Pilot",
    "Prelude",
    "Ridgeline",
    "S2000"
  ],
  Audi: [
    "100",
    "200",
    "80",
    "90",
    "A3",
    "A4",
    "A5",
    "A6",
    "A7",
    "A8",
    "AllRoad",
    "AllRoad A4",
    "Cabriolet",
    "Coupe Quattro",
    "Q3",
    "Q5",
    "Q7",
    "R8",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "S3",
    "S4",
    "S5",
    "S6",
    "S7",
    "S8",
    "SQ5",
    "TT",
    "V8 Quattro"
  ],
  Mazda: [
    "2",
    "3",
    "5",
    "6",
    "626",
    "CX5",
    "CX7",
    "CX9",
    "Miata MX5",
    "MPV Van",
    "MX3",
    "Pickup-B2300",
    "Pickup-B2500",
    "Pickup-B3000",
    "Pickup-B4000",
    "Protege",
    "RX8",
    "Tribute"
  ],
  Lincoln: [
    "Aviator",
    "Blackwood",
    "Continental",
    "LS",
    "Mark LT",
    "MKC",
    "MKS",
    "MKT",
    "MKX",
    "MKZ",
    "Navigator",
    "Other (includes Town Car)",
    "Zephyr"
  ],
  Saturn: [
    "Astra",
    "Aura",
    "Ion",
    "L Series",
    "Outlook",
    "Relay",
    "S Series",
    "Sky",
    "Vue"
  ],
  Dodge: [
    "600",
    "Aries",
    "Avenger",
    "Caliber",
    "Caravan",
    "Challenger (Chrysler)",
    "Charger",
    "D50/Ram 50",
    "Dakota",
    "Dart",
    "Daytona",
    "Diplomat",
    "Durango",
    "Dynasty",
    "Intrepid",
    "Journey",
    "Magnum",
    "Neon",
    "Nitro",
    "Ramcharger",
    "Rampage",
    "Shadow",
    "Spirit",
    "St Regis",
    "Stealth",
    "Stratus",
    "Truck-150",
    "Truck-1500",
    "Truck-250",
    "Truck-2500",
    "Truck-350",
    "Truck-3500/ 4500 / 5500",
    "Van 150",
    "Van 1500",
    "Van 250",
    "Van 2500",
    "Van 350",
    "Van 3500",
    "Van (Sprinter 2500)",
    "Van (Sprinter 3500)"
  ],
  cadillac: [
    "ATS",
    "Catera",
    "Concours",
    "CT6",
    "CTS",
    "DeVille",
    "DTS",
    "DTS (2006 Up)",
    "ELR",
    "Escalade",
    "Escalade-ESV",
    "Escalade-EXT",
    "Seville (incl STS)",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5"
  ],
  Chrysler: [
    "200",
    "300",
    "300M",
    "Aspen",
    "Cirrus",
    "Concorde",
    "Crossfire",
    "Fifth Avenue - FWD",
    "Imperial",
    "LHS",
    "Lebaron",
    "New Yorker - FWD",
    "Pacifica",
    "Prowler",
    "PT Cruiser",
    "Sebring",
    "TC",
    "Town and Country",
    "Voyager"
  ],
  Jeep: [
    "Cherokee (except Grand Cherokee)",
    "Commander",
    "Comanche",
    "Compass",
    "Grand Cherokee",
    "Liberty",
    "Patriot",
    "Renegade",
    "Wagoneer",
    "Wagoneer (except Grand Wagoneer)",
    "Wrangler"
  ],
  Mercedes: [
    "190",
    "300D (includes CD/D/SD/TD)",
    "300E",
    "300SL",
    "350",
    "400",
    "420",
    "500",
    "560",
    "600",
    "A Class",
    "AMG GT",
    "B Class",
    "C Class",
    "CL Class",
    "CLA Class",
    "CLK",
    "CLS",
    "E Class",
    "G Class",
    "GL Class",
    "GLA Class",
    "GLB Class",
    "GLC Class",
    "GLE Class",
    "GLK Class",
    "GLS Class",
    "ML Series",
    "Metris",
    "R Class",
    "S Class",
    "SL Class",
    "SLC Class",
    "SLK",
    "SLR",
    "SLS",
    "Sprinter 1500",
    "Sprinter 2500",
    "Sprinter 3500"
  ],
  infiniti: [
    "EX35",
    "EX37",
    "FX",
    "G20",
    "G25",
    "G35",
    "G37",
    "I30",
    "I35",
    "JX35",
    "M30",
    "M35",
    "M37",
    "M45",
    "M56",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX4",
    "QX30",
    "QX50",
    "QX56",
    "QX60",
    "QX70",
    "QX80"
  ],
  subaru: [
    "Baja",
    "BRZ",
    "Forester",
    "Impreza",
    "Justy",
    "Legacy",
    "Loyale",
    "Outback (Impreza)",
    "Outback (Legacy)",
    "SVX",
    "Tribeca",
    "WRX",
    "XT",
    "XV Crosstrek"
  ],
  Buick: [
    "Allure",
    "Cascada",
    "Century",
    "Enclave",
    "Encore",
    "Envision",
    "Lacrosse",
    "LeSabre",
    "Lucerne",
    "Park Ave",
    "Rainier",
    "Regal",
    "Rendezvous",
    "Riviera",
    "Skylark",
    "Terraza",
    "Verano"
  ],
  Nissan: [
    "200SX",
    "240SX",
    "300ZX",
    "350Z",
    "370Z",
    "Altima",
    "Armada",
    "Axxess",
    "Cube",
    "Frontier",
    "GTR",
    "Juke",
    "Leaf",
    "Maxima",
    "Micra",
    "Murano",
    "NV 1500",
    "NV 200",
    "NV 2500",
    "NV 3500",
    "NX",
    "Pathfinder",
    "Pulsar",
    "Qashqai",
    "Quest",
    "Rogue",
    "Rogue Sport",
    "Sentra",
    "Stanza (Excl Van)",
    "Truck",
    "Truck-Titan",
    "Truck-Titan XD",
    "Versa",
    "X Trail",
    "Xterra"
  ],
  Volvo: [
    "30 Series",
    "40 Series",
    "50 Series",
    "60 Series",
    "70 Series",
    "80 Series",
    "850",
    "90 Series",
    "S60",
    "S90",
    "V60",
    "V70",
    "V90",
    "XC40",
    "XC60",
    "XC70",
    "XC90"
  ],
  Porsche: [
    "911/930",
    "918",
    "944",
    "Boxster",
    "Cayenne",
    "Cayman S",
    "Macan",
    "Panamera"
  ],
  Acura: [
    "CSX",
    "EL",
    "ILX",
    "Integra",
    "Legend",
    "MDX",
    "NSX",
    "RDX",
    "RL",
    "RLX",
    "RSX",
    "SLX",
    "TL",
    "TLX",
    "TSX",
    "Vigor",
    "ZDX"
  ],
  BMW: [
    "1M",
    "128i",
    "135i",
    "228i",
    "230i",
    "318i",
    "320i",
    "323i",
    "325i",
    "328i",
    "328i GT",
    "330e",
    "330i",
    "330i GT",
    "335i",
    "335i GT",
    "340i",
    "340i GT",
    "428i",
    "430i",
    "435i",
    "440i",
    "525i",
    "528i",
    "530e",
    "530i",
    "535i",
    "535i GT",
    "540i",
    "550i",
    "550i GT",
    "640i",
    "640i GT",
    "645Ci",
    "650i",
    "740e",
    "740i",
    "745e",
    "745i",
    "750i",
    "760i",
    "840ci",
    "840i",
    "850i",
    "ActiveHybrid 3",
    "ActiveHybrid 5",
    "ActiveHybrid 7",
    "Alpina B6",
    "Alpina B7",
    "I3",
    "I8",
    "M2",
    "M235i",
    "M240i",
    "M3",
    "M4",
    "M5",
    "M6",
    "M8",
    "M550i",
    "M760i",
    "M850i",
    "Mini Cooper",
    "Mini Cooper Clubman",
    "Mini Cooper Countryman",
    "Mini Cooper Paceman",
    "X1",
    "X2",
    "X3",
    "X4",
    "X5",
    "X5M",
    "X6",
    "X6M",
    "X7",
    "Z3",
    "Z4",
    "Z8"
  ],
  suzuki: [
    "Aerio",
    "Equator",
    "Esteem",
    "Forenza",
    "Kizashi",
    "Reno",
    "Samurai",
    "Sidekick",
    "Swift",
    "SX4",
    "Verona",
    "Vitara",
    "X90",
    "XL7"
  ],
  chevy: [
    "Astro",
    "Aveo",
    "Beretta",
    "Blazer",
    "Blazer, Full Size",
    "Blazer, S10/S15",
    "Camaro",
    "Caprice",
    "Captiva Sport",
    "Cavalier",
    "Celebrity",
    "City Express",
    "Cobalt",
    "Corsica",
    "Corvette",
    "Cruze",
    "El Camino",
    "Epica",
    "Equinox",
    "HHR",
    "Impala",
    "Lumina Car",
    "Lumina Van",
    "Malibu",
    "Metro",
    "Monte Carlo",
    "Optra",
    "Orlando",
    "Prizm",
    "S10/S15/Sonoma",
    "Sonic",
    "Spark",
    "Sprint",
    "SS",
    "SSR",
    "Suburban-1500",
    "Suburban-2500",
    "Suburban-3500",
    "Tahoe",
    "Tracker",
    "TrailBlazer",
    "TrailBlazer-EXT",
    "Traverse",
    "Trax",
    "Truck-1500",
    "Truck-2500",
    "Truck-3500",
    "Truck-Avalanche 1500",
    "Truck-Avalanche 2500",
    "Truck-Colorado",
    "Truck-Forward Control",
    "Truck-S10/S15/Sonoma",
    "Truck-Silverado 1500",
    "Truck-Silverado 2500",
    "Truck-Silverado 3500",
    "Uplander",
    "Van 10",
    "Van 20",
    "Van 30",
    "Van Express 1500",
    "Van Express 2500",
    "Van Express 3500",
    "Venture",
    "Volt"
  ],
  Lexus: [
    "CT 200H",
    "ES250",
    "ES300",
    "ES300H",
    "ES330",
    "ES350",
    "GS200t",
    "GS300",
    "GS350",
    "GS400",
    "GS430",
    "GS450",
    "GS460",
    "GS F",
    "GX460",
    "GX470",
    "HS250H",
    "IS200t",
    "IS250",
    "IS300",
    "IS350",
    "IS F",
    "LC500",
    "LC500h",
    "LS400",
    "LS430",
    "LS460",
    "LS500",
    "LS500h",
    "LS600HL",
    "LX450",
    "LX470",
    "LX570",
    "NX200t",
    "NX300",
    "NX300h",
    "RC 200t",
    "RC 300",
    "RC 350",
    "RC F",
    "RX300",
    "RX330",
    "RX350",
    "RX350L",
    "RX400h",
    "RX450 Hybrid",
    "RX450 Hybrid L",
    "SC (excl 430)",
    "SC430",
    "UX 250h"
  ],
  Toyota: [
    "4Runner",
    "86",
    "Avalon",
    "CHR",
    "Camry",
    "Celica",
    "Corolla",
    "Corolla Cross",
    "Corolla iM",
    "Cressida",
    "Echo",
    "FJ Cruiser",
    "GR Supra",
    "GR86",
    "Highlander",
    "Land Cruiser",
    "Matrix",
    "Mirai",
    "MR2",
    "Paseo",
    "Previa",
    "Prius",
    "RAV4",
    "RAV5",
    "Sequoia",
    "Sienna",
    "Solara",
    "Supra",
    "T100",
    "Tacoma",
    "Tercel",
    "Truck (except T100 & Tundra)",
    "Tundra",
    "Van",
    "Venza",
    "Yaris",
    "Yaris iA"
  ]
};

export const YEARS = [
  "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999",
  "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009",
  "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018"
];
